[build]
base = "Pokemon-Frontend"
command = "npm run prerender"
publish = "Pokemon-Frontend/dist/pokemon-frontend/browser"

[dev]
command = "npm run start"
functions = "./functions"
publish = "Pokemon-Frontend/src"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
